### PR TITLE
Allow users to choose how many reps / iters and what vec size they want.

### PR DESCRIPTION
**Pull request by ltratt**
If left unspecified, it reverts to the previous defaults.

### CODE REVIEW

**Comment by ltratt** [comment]
[I forgot to run rustfmt. Mea culpa!]

**Comment by vext01** [comment]
LGTM. Shall I merge?

**Comment by ltratt** [comment]
I should squash, if you're OK with that?

**Comment by vext01** [comment]
Go ahead

**Comment by vext01** [comment]
Hold up, where's the rustfmt config?

**Comment by ltratt** [comment]
Good point. I've used the defaults... Let me fix that.

**Comment by ltratt** [comment]
OK, pushed. I suggest I squash the two rustfmt commits into one so that it doesn't mess our idea of the main change.

**Comment by vext01** [comment]
Agreed, go ahead.

**Comment by ltratt** [comment]
Squashed.

**Pull request merged**
